name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZ_HOST }}
          username: ${{ secrets.AZ_USERNAME }}
          key: ${{ secrets.AZ_KEY }}
          source: "tutoriais"
          target: "."
      - name: Pull and up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZ_HOST }}
          username: ${{ secrets.AZ_USERNAME }}
          key: ${{ secrets.AZ_KEY }}
          script: |
            sudo docker compose up -d
